import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Scrollbar from "@/components/scrollbar";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jam's Closet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" min-h-screen flex flex-col gap-2">
        <Scrollbar/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}



